Summary
Max7433/icecream_lending_t4.1 pull request #20
Opened 2022-08-09 12:20 UTC by IngaPirogova

Шрифты. Папка в корне проекта fonts со шрифтами и в папке sass/utils/_fonts.scss ссылка подключения через @import

2022-08-09 16:49 UTC, Max7433 requested changes
Надо подключить импортом в _modul.scss < _fonts.scss

2022-08-09 17:31 UTC, Max7433 requested changes

2022-08-09 17:31 UTC, Max7433 commented on src/sass/layouts/_modul.scss
> +@import '../utils/fonts';
Внимательней не сюда
в utils/modul.scss

2022-08-10 10:56 UTC, Tkachenko-Yuriy approved these changes

2022-08-10 11:23 UTC, merged